### ISSUE TITLE
Bring back continuous integration

### ISSUE THREAD

**Issue by marcua** [b12io/metronome#12]
When we open sourced metronome, we didn't copy over the CI configuration from our closed source copy. Here are the contents of the original `.circleci/config.yml`:

```
version: 2
jobs:
  build:
    working_directory: ~/design-system
    docker:
        - image: node:10.15.3
    steps:
      - checkout
      - run: apt-get update && apt-get install -y build-essential
      - run: yarn
      - run: yarn flow
      - run: yarn test --maxWorkers=2 --coverage
      - store_artifacts:
          path: ~/design-system/coverage_report/lcov-report
```

I'd be a proponent for using GitHub actions, but don't feel strongly and am happy if we use CircleCI as well.
